kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq-amsroute 
  namespace: mq 
spec:
  host: tls3.chl.mq.ibm.com
  to:
    kind: Service
    name: mq-ams-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
