kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq-amsroute-consumer-app
  namespace: consumer-app
spec:
  host: tls3.consumerapp.chl.mq.ibm.com
  to:
    kind: Service
    name: mq-ams-consumer-app-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
