apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq-ams
  namespace: mq
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
   # license: L-RJON-BN7PN3
    metric: VirtualProcessorCore
    use: Development
  queueManager:
    # image: image-registry.openshift-image-registry.svc:5000/mq/demomq:v0.2
    imagePullPolicy: Always
    storage:
      defaultClass: ibmc-block-gold
      queueManager:
        type: persistent-claim
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 4Gi
    availability:
      updateStrategy: RollingUpdate
    #  type: SingleInstance
      type: NativeHA
    name: QMAMS
    mqsc:
    - configMap:
        name: ams1-mqsc
        items:
        - ivt.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'no'
            - name: MQS_KEYSTORE_CONF
              value: '/opt/mqm/ams/keystore.conf'
            - name: AMQ_CLOUD_PAK
              value: 'true'
          name: qmgr
          volumeMounts:
        # name must match the volume name below
            - name: kdb
              mountPath: /opt/mqm/ams
              readOnly: true
            - name: conf
              mountPath: /opt/mqm/ams
              readOnly: true
      volumes:
        - name: kdb
          secret:
            secretName: kdb-secret
        - name: conf
          secret:
            secretName: ams-conf
  version: 9.3.4.0-r1
  web:
    enabled: true
  mqDashboard: true
  pki:
    keys:
      - name: label1
        secret:
          secretName: mqamskey
          items:
            - tls.key
            - tls.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
