apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq2
  namespace: mq
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
   # license: L-RJON-BN7PN3
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    image: image-registry.openshift-image-registry.svc:5000/mq/demomq:v0.1
    imagePullPolicy: Always
    storage:
      defaultClass: ibmc-block-gold
      queueManager:
        type: persistent-claim
    resources:
      limits:
        cpu: '1'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 4Gi
    availability:
      updateStrategy: RollingUpdate
      type: SingleInstance
   #   type: NativeHA
    name: QM1
    mqsc:
    - configMap:
        name: ams1-mqsc
        items:
        - ivt.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
            - name: MQS_KEYSTORE_CONF
              value: '/run/keystore.conf'
          name: qmgr
  version: 9.3.0.0-r2
  web:
    enabled: true
  mqDashboard: true
  tracing:
    enabled: false
    namespace: od
  pki:
    keys:
      - name: label1
        secret:
          secretName: mq2key
          items:
            - tls.key
            - tls.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
