apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    wbg/app_repo_config_git_url: 'https://bitbucket.srv.westpac.com.au/scm/a0076b/wbg_a0076b_mq_container_config.git'
    wbg/pipeline_run: 'https://console-openshift-console.apps.ocp-rcc-npr-waz-04.ocp.srv.westpac.com.au/k8s/ns/mws-cicd/tekton.dev~v1beta1~PipelineRun/testing-scripts'
    meta.helm.sh/release-namespace: a0076b-sit
    com.ibm.mq/write-defaults-spec: 'false'
    meta.helm.sh/release-name: ludgn992
    wbg/app_repo_config_git_revision: develop
    applicationServices: Middleware Services - Test
    wbg/deployed_time: '2024-06-27T10:37:28'
    serviceOffering: MQ Containers Offering (MQCaaS) - NonProd
    infraEnv: npr
    wbg/wbg_ibm_mq_chart_version: 930.17.1
  name: ludgn992-qmgr
  namespace: mq
  finalizers:
    - finalizer.queuemanagers.mq.ibm.com
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  license:
    accept: true
    license: L-JTPV-KYG8TF
    metric: VirtualProcessorCore
    use: NonProduction
  annotations:
    wbg/app_repo_config_git_url: 'https://bitbucket.srv.westpac.com.au/scm/a0076b/wbg_a0076b_mq_container_config.git'
    wbg/pipeline_run: 'https://console-openshift-console.apps.ocp-rcc-npr-waz-04.ocp.srv.westpac.com.au/k8s/ns/mws-cicd/tekton.dev~v1beta1~PipelineRun/testing-scripts'
    prometheus.io/port: '9157'
    wbg/app_repo_config_git_revision: develop
    applicationServices: Middleware Services - Test
    splunk.com/include: 'true'
    wbg/deployed_time: '2024-06-27T10:37:28'
    prometheus.io/scrape: 'true'
    serviceOffering: MQ Containers Offering (MQCaaS) - NonProd
    infraEnv: npr
    wbg/wbg_ibm_mq_chart_version: 930.17.1
  terminationGracePeriodSeconds: 30
  pki:
    keys:
      - name: label1
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: mqamskey
  securityContext:
    initVolumeAsRoot: false
  web:
    enabled: false
  version: 9.4.0.0-r1
  template:
    pod:
      containers:
        - env:
            - name: MQS_KEYSTORE_CONF
              value: '/var/mqm/ams/keystore.conf'
            - name: AMQ_NO_BAD_COMMS_DATA_FDCS
              value: 'true'
          name: qmgr
          resources: {}
          #volumeMounts:
          #  - mountPath: /mnt/scripts
          #    name: cm-ludgn992-ibm-mq-scripts
          #  - mountPath: /mqdumps
          #    name: dumps
      initContainers:
        - command:
            - sh
            - '-c'
            - mkdir -p /mnt/mqm/data/ams && cp /qmgr_tls/* /mnt/mqm/data/ams && cp /qmgr_conf/* /mnt/mqm/data/ams
          image: 'busybox:latest'
          name: copy-qmgr-tls
          resources: {}
          volumeMounts:
            - mountPath: /qmgr_tls
              name: secret-ludgn992-trust
            - mountPath: /qmgr_conf
              name: secret-ludgn992-conf
              readOnly: true
            - mountPath: /mnt/mqm
              name: data
      volumes:
        #- configMap:
        #    defaultMode: 493
        #    name: ludgn992-ibm-mq-scripts
        #  name: cm-ludgn992-ibm-mq-scripts
        #- name: dumps
        #  persistentVolumeClaim:
        #    claimName: dump-ludgn992-qmgr-ibm-mq
        - name: secret-ludgn992-trust
          secret:
            defaultMode: 420
            items:
              - key: ams.kdb
                path: ams.kdb
              - key: ams.sth
                path: ams.sth
            secretName: kdb-secret
        - name: secret-ludgn992-conf
          secret:
            defaultMode: 420
            items:
              - key: keystore.conf
                path: keystore.conf 
            secretName: ams-conf 
  queueManager:
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    route:
      enabled: true
    name: LUDGN992
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    debug: false
    startupProbe:
      failureThreshold: 24
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    mqsc:
      - configMap:
          items:
            - ivt.mqsc
          name: ams1-mqsc
    logFormat: Basic
    availability:
      type: NativeHA
      updateStrategy: RollingUpdate
    storage:
      defaultClass: ocs-storagecluster-ceph-rbd
      persistedData:
        enabled: false
      queueManager:
        deleteClaim: false
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false
